### ISSUE TITLE
Wrong accent colour

### ISSUE THREAD

**Issue by infinitepower18** [Akascape/py-window-styles#15]
The accent colour being returned doesn't match with the rest of the system. Notice the difference in the button colour of my app compared to the MS Store's install button.

<img width="518" alt="image" src="https://github.com/Akascape/py-window-styles/assets/44692189/837ac37a-3b45-4f4d-b219-4e69f1fedafd">

**Comment by littlewhitecloud** [comment]
![image](https://github.com/Akascape/py-window-styles/assets/71159641/d84ee668-c9cc-4c86-81bf-9b9e207b24d3)

**Comment by Akascape** [comment]
@infinitepower18 I am not getting the wrong color, it is simply giving the windows accent color. (Compare with the settings widgets)
![Screenshot](https://github.com/Akascape/py-window-styles/assets/89206401/75684c84-0b3a-4b27-9c98-1be9bbaf8c0b)

Secondly, the button color of microsoft store is little bit light in color, maybe because of the themes they have used.

![Screenshot 2](https://github.com/Akascape/py-window-styles/assets/89206401/32fda3d0-e588-457e-9c61-fd6e0fb43b83)

**Comment by Valer100** [comment]
@infinitepower18 If you want to get the dark mode accent color, you can use my Python module [winaccent](https://github.com/Valer100/winaccent).

**Comment by infinitepower18** [comment]
> @infinitepower18 If you want to get the dark mode accent color, you can use my Python module [winaccent](https://github.com/Valer100/winaccent).

@Valer100 thanks, I'll take a look
